[build]
  command = "npm install"
  functions = "."  # Functions directory is the root
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true